CREATE TABLE IF NOT EXISTS activity (
    date DATE PRIMARY KEY,
    total_steps INT,
    total_distance_meters FLOAT,
    active_seconds INT,
    sedentary_seconds INT,
    moderate_intensity_minutes INT,
    vigorous_intensity_minutes INT,
    total_calories FLOAT,
    active_calories FLOAT,
    resting_calories FLOAT,
    min_heart_rate INT,
    max_heart_rate INT,
    resting_heart_rate INT,
    stress_duration INT,
    total_stress_duration INT,
    measurable_awake_duration INT,
    measurable_asleep_duration INT,
    body_battery_highest INT,
    body_battery_lowest INT,
    body_battery_most_recent INT,
    avg_respiration FLOAT,
    highest_respiration FLOAT,
    lowest_respiration FLOAT,
    avg_spo2 FLOAT,
    lowest_spo2 FLOAT
);
